### PR TITLE
Wording fix in statement

### PR DESCRIPTION
**Pull request by sha1sum**
I believe this is what was intended here.

### CODE REVIEW

**Comment by thenewdarling** [comment]
Obviously I'm just another person watching this repo but the content of this pull request is confusing me, haha

[original meaning pre pull request] "Other people's grieving processes might look different than yours would, and you shouldn't police how people behave in traumatising situations."

[this pull request change] "You shouldn't tell people specifically that they should be happy when someone/something dies."

Do I have that right or am I misinterpreting what you're changing?

**Comment by sha1sum** [comment]
@thenewdarling it's more an attempt to fix a grammatical error not a message change. If you take the contraction out of the original it reads `no one benefits from you telling them they are being sad wrong`, which doesn't make much sense.

**Comment by sha1sum** [comment]
I closed the pull request, as I guess I'm the one misinterpreting this. My apologies.

**Comment by thenewdarling** [comment]
@sha1sum Ahh I see where you are coming from, however it is grammatically correct. Compare to "No-one benefits from you telling them they are making a sandwich wrong". 

'Wrong' is less formal than eg using the word "incorrectly" but it's still a valid way to express the idea.

(Ironically I don't know how many people are benefitting from me telling them they are submitting a pull request wrong 😆)

**Pull request closed without merging**
